import { repositoryRoot } from "./test-helpers.ts";

export const expectedCreateEnvironmentCommands: string[][] = [
  [
    "herdr",
    "workspace",
    "create",
    "--cwd",
    repositoryRoot,
    "--no-focus",
    "--label",
    "review: stack-review",
  ],
  ["herdr", "tab", "rename", "wB:t1", "control"],
  [
    "herdr",
    "tab",
    "create",
    "--workspace",
    "wB",
    "--cwd",
    repositoryRoot,
    "--no-focus",
    "--label",
    "1 core",
  ],
  [
    "herdr",
    "tab",
    "create",
    "--workspace",
    "wB",
    "--cwd",
    repositoryRoot,
    "--no-focus",
    "--label",
    "2 hunk-session",
  ],
  [
    "herdr",
    "tab",
    "create",
    "--workspace",
    "wB",
    "--cwd",
    repositoryRoot,
    "--no-focus",
    "--label",
    "3 herdr-layout",
  ],
  ["hunk", "session", "list", "--json"],
  ["herdr", "pane", "run", "wB:p2", "hunk diff trunk-commit..core"],
  ["hunk", "session", "list", "--json"],
  ["hunk", "session", "list", "--json"],
  ["herdr", "pane", "run", "wB:p3", "hunk diff core-commit..hunk-session"],
  ["hunk", "session", "list", "--json"],
  ["hunk", "session", "list", "--json"],
  ["herdr", "pane", "run", "wB:p4", "hunk diff hunk-commit..herdr-layout"],
  ["hunk", "session", "list", "--json"],
  ["herdr", "workspace", "focus", "wB"],
  ["herdr", "tab", "focus", "wB:t1"],
];
